[workspace]
resolver = "3"

members = ["crates/*"]
default-members = ["crates/elf2flash"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace.dependencies]
log = "0.4"
thiserror = "2"
rusb = { version = "0.9" }
