name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish-elf2flash:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    needs:
      - elf2flash
    with:
      crate: elf2flash
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-elf2flash-core:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v4
    with:
      crate: elf2flash-core
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}
